#!/usr/bin/bash

set -e
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
url="$1"
res="$2"

[ -z "$url" ] && {
	read -ep 'Video URL: ' url
}

printf "Downloading Webpage..\n"
curl -fsSL "$url" -o $tmp

url=$(grep mp4\? $tmp|sed 's/https:\\\/\\\//\nhttps:\\\/\\\//g'|grep ^http|sed 's/\",/\n/g'|grep 'media\\/mp4\?'|sort|uniq)
title=$(grep -i videotitle $tmp|cut -d':' -f2|tr ' ' '_')
title="${title#_}"

curl -fsSL "${url//\\/}" -o $tmp

urls=($(sed -e 's/quality\":/\n/g' -e 's/}/\n/g' $tmp |grep http|sed -e 's/,\"videoUrl\":/|/g'))

urls=("${urls[@]//\\/}")

printf '%s\n' ${urls[@]//\"/} >$tmp

[ -z "$res" ] && {
	rs=($(cat $tmp|cut -d'|' -f1))
	echo ${rs[@]}
	read -ep 'Quality ? ' res
}

url=$(grep ^$res $tmp|cut -d'|' -f2)
size=$(curl -fsSLI "$url" |grep -i content-length|dos2unix|cut -d' ' -f2|numfmt --to=iec-i)

printf "Download size: ${size}B\n"

read -en1 -p 'Continue [Yn]? ' yn

[[ -z "$yn" || "$yn" == [Yy] ]]||exit 1

t=$(echo "${title%,}"|tr -d '"')

hash aria2c 2>/dev/null && aria2c "$url" -o "$t.mp4" && exit
curl -C - -fL "$url" -o "$t.mp4"
