#!/usr/bin/bash
set -e

[ $# -ne 1 ] && read -ep 'Video URL: ' u
[ -z "$u" ] && exit

ua="Mozilla/5.0 (Linux; Android 11; RMX2156) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.5938.154 Mobile Safari/537.36 OPR/78.4.4143.75735"

urls=(`curl -A "$ua" -sL "$u" |grep -E 'lLow|lHigh'|cut -d"'" -f2`)

size=(`curl -A "$ua" -sLI "${urls[@]}"|grep -i content-length|cut -d' ' -f2|dos2unix|numfmt --to=iec`)

for i in ${!size[@]}; do
	echo "$i : ${size[i]}"
done

read -en1 -p 'Download: ' j
[ -z "$j" ] && exit

curl -A "$ua" -LO ${urls[j]}
