#!/usr/bin/bash

set -e
lk="$1"
ql="$2"

rl() {
	[ -z "$lk" ] && read -ep 'XNXX Video URL: ' lk
	[ -z "$ql" ] && read -en1 -p "Quality?[L]ow/[H]igh? " ql
}

[ $# -ne 2 ] && rl

[[ "$ql" != [LlHh] ]] && exit 1

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
curl -fsSL "$lk" -o $tmp

title=$(grep '<title>' "$tmp"|sed -e 's/<[^>]*>//g' -e 's/[^[:print:]]//g' -e 's/\s/_/g')

et() {
	cat $tmp |sed -e 's/http/\nhttp/g'|grep Qual|sed -e 's/Qual/\n/g' -e 's/">View//g'|grep -i $1|awk '{print $1}'
}

[[ "$ql" = [Hh] ]] && vd=$(et High) || vd=$(et Low)

size=$(curl -fsSLI "$vd"|grep -i Content-Length | awk '{print $2}'|dos2unix|numfmt --to=si)

echo "Download size: $size"
read -en1 -p "Continue [yn]? " yn
[[ "$yn" != [Yy] ]] && exit 1
curl -fL "$vd" -o "$title.mp4"
